### PR TITLE
Improve zone handling to support multiple matches

### PR DESCRIPTION
**Pull request by mhiguera**
Refactored the zone lookup logic to support multiple matching preset and instrument zones for a given key. The code now filters for all matching zones instead of returning just the first match, allowing for more accurate sample and generator handling across multiple instrument zones.

### CODE REVIEW

**Review by Mrtenz — APPROVED** [review]
I have no way to verify that this works (as I don't really use soundfonts anymore), but I think this makes sense. Thanks!

**Comment by mhiguera** [comment]
Thank you Maarten for accepting my Pull Request and for the amazing work you've done on the project!

**Comment by henrikvilhelmberglund** [comment]
Could a new release be made for this? I'm having trouble installing from a commit hash and the fork doesn't have this PR applied.

**Comment by Mrtenz** [comment]
Hi @henrikvilhelmberglund, I published a new version as `soundfont2@0.5.0`. Thanks for the reminder!

**Pull request merged**
